{
    "clientName": "Client Name",
    "companyName": "Company Name"
}
"pageTitle": "Log in | ${clientName}",
"title": "Welcome",
"description": "Log in to ${companyName} to continue to ${clientName}.",
"separatorText": "Or",
"buttonText": "Continue",
"federatedConnectionButtonText": "Continue with ${connectionName}",
"footerLinkText": "Sign up",
"signupActionLinkText": "${footerLinkText}",
"footerText": "Don't have an account?",
"signupActionText": "${footerText}",
"forgotPasswordText": "Forgot password?",
"passwordPlaceholder": "Password",
"usernamePlaceholder": "Username or email address",
"emailPlaceholder": "Email address",
"phonePlaceholder": "Phone number",
"usernameOnlyPlaceholder": "Username",
"phoneOrUsernameOrEmailPlaceholder": "Phone or Username or Email",
"phoneOrEmailPlaceholder": "Phone number or Email address",
"phoneOrUsernamePlaceholder": "Phone Number or Username",
"usernameOrEmailPlaceholder": "Username or Email address",
"editEmailText": "Edit",
"alertListTitle": "Alerts",
"invitationTitle": "You've Been Invited!",
"invitationDescription": "Log in to accept ${inviterName}'s invitation to join ${companyName} on ${clientName}.",
"captchaCodePlaceholder": "Enter the code shown above",
"logoAltText": "${companyName}",
"showPasswordText": "Show password",
"hidePasswordText": "Hide password",
"wrong-credentials": "Wrong username or password",
"wrong-email-credentials": "Wrong email or password",
"wrong-username-credentials": "Incorrect username or password",
"wrong-phone-credentials": "Incorrect phone number or password",
"wrong-email-username-credentials": "Incorrect email address, username, or password",
"wrong-email-phone-username-credentials": " Incorrect email address, phone number, username, or password. Phone numbers must include the country code.",
"wrong-email-phone-credentials": "Incorrect email address, phone number, or password. Phone numbers must include the country code.",
"wrong-phone-username-credentials": "Incorrect phone number, username or password. Phone numbers must include the country code.",
"invalid-code": "The code you entered is invalid",
"invalid-expired-code": "Invalid or expired user code",
"custom-script-error-code": "Something went wrong, please try again later.",
"auth0-users-validation": "Something went wrong, please try again later",
"authentication-failure": "We are sorry, something went wrong when attempting to log in",
"invalid-connection": "Invalid connection",
"ip-blocked": "We have detected suspicious login behavior and further attempts will be blocked. Please contact the administrator.",
"no-db-connection": "Invalid connection",
"password-breached": "We have detected a potential security issue with this account. To protect your account, we have prevented this login. Please reset your password to proceed.",
"user-blocked": "Your account has been blocked after multiple consecutive login attempts.",
"same-user-login": "Too many login attempts for this user. Please wait, and try again later.",
"no-email": "Please enter an email address",
"no-password": "Password is required",
"no-username": "Username is required",
"captcha-validation-failure": "We are sorry, something went wrong while validating the captcha response. Please try again.",
"invalid-recaptcha": "Select the checkbox to verify you are not a robot.",
"invalid-captcha": "Solve the challenge question to verify you are not a robot.",
"captcha-client-failure": "We couldn’t load the security challenge. Please try again. (Error code: #{errorCode})"
}